modLoader = "javafml"
loaderVersion = "[32,)"
issueTrackerURL = "https://github.com/team-abnormals/bamboo-blocks/issues"
license = "https://github.com/team-abnormals/bamboo-blocks/blob/main/LICENSE.txt"

[[mods]]
    modId = "bamboo_blocks"
    version = "${file.jarVersion}"
    logoFile = "logo.png"
    authors = "Team Abnormals"
    credits = "Endergized, bageldotjpg, Farcr"
    displayName = "Bamboo Blocks"
    description = '''
    Fun Bamboo Blocks to build with!
    '''

[[dependencies.bamboo_blocks]]
    modId = "forge"
    mandatory = true
    versionRange = "[32.0.72,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.bamboo_blocks]]
    modId = "abnormals_core"
    mandatory = true
    versionRange = "[2.0.6,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.bamboo_blocks]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.16.1]"
    ordering = "NONE"
    side = "BOTH"